core/urls.py
from django.urls import path


from core.views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

pages/urls.py
from django.urls import path
from . import views
from pages.views import PagesListView, PageDetailView, PageCreate, PageUpdate, PageDelete

app_name = 'pages'

urlpatterns = [
    path('', PagesListView.as_view(), name='pages'),
    path('create/', PageCreate.as_view(), name='create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name='delete'),
    path('<int:pk>/<slug:slug>/', PageDetailView.as_view(), name='page'),
]

registration/urls.py
from django.urls import path

from .views import SignUpView, ProfileUpdate, EmailUpdate

urlpatterns = [
    # Registro
    path('signup/', SignUpView.as_view(), name='signup'),
    # Perfil de usuario
    path('profile/', ProfileUpdate.as_view(), name='profile'),
    # Perfil, editar email
    path('profile/email/', EmailUpdate.as_view(), name='profile_email')

]

webground/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),

    # Rutas de autenticacion
    # Login
    path('accounts/', include('django.contrib.auth.urls')),
    # Register
    path('accounts/', include('registration.urls'))

]


# Configuración para el cargue de las Imagenes
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

#Modelo User, de django

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

profiles/models.py
from django.db import models

# Create your models here.

pages/forms.py
# clase de formularios para heredar.
from django import forms
# Modelo Page
from .models import Page


class PageForm(forms.ModelForm):
    class Meta:
        model = Page

        # fields = ['title', 'content', 'order']
        # Hace referencia a todos los campos del modelo, apareceran en orden de acuerdo al modelo
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Titulo'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'order': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Orden'})
        }

        labels = {
            'title': '',
            'content': '',
            'order': ''
        }

core/views.py
from django.shortcuts import render

# Vista generica: TemplateView
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = 'core/home.html'

    """ Render function(traditional)"""
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': 'Contexto con reder'})

class SamplePageView(TemplateView):
    template_name = "core/sample.html"

pages/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse, reverse_lazy
from .models import Page


#Dorator de validacion - staff
from django.contrib.admin.views.decorators import staff_member_required
#Metodo decorador
from django.utils.decorators import method_decorator

# Importar vista generica 'ListView'
from django.views.generic import ListView
# Importar vista generica 'DetailView'
from django.views.generic import DetailView
# Importar vista generica 'CreateView'
from django.views.generic import CreateView
# Importar vista generica 'UpdateView' y 'DeleteView'
from django.views.generic.edit import UpdateView, DeleteView

# Modelo del formulario
from .forms import PageForm


class StaffRequiredMixin(object):
    """
    Este mixin requerira que el usuario sea miembro del staff

    """
    @method_decorator(staff_member_required())
    def dispatch(self, request, *args, **kwargs):
        #if not request.user.is_staff:
        #    return redirect(reverse_lazy('admin:login'))
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)


# Create your views here.
class PagesListView(ListView):
    model = Page
    # por defecto el asigna como nombre de tamplate <pages/model_name_list.html>
    # template_name = ''


class PageDetailView(DetailView):
    model = Page
    # por defecto el asigna como nombre de tamplate <pages/model_name_list.html>
    # template_name = ''


@method_decorator(staff_member_required(), name='dispatch')
class PageCreate(CreateView):
    model = Page
    form_class = PageForm
    #fields = ['title', 'content', 'order']
    # por defecto el asigna como nombre de tamplate <pages/model_name_list.html>
    # template_name = ''

    # def get_success_url(self):
    #    return reverse('pages:pages')

    # Redirect
    success_url = reverse_lazy('pages:pages')

@method_decorator(staff_member_required(), name='dispatch')
class PageUpdate(UpdateView):
    model = Page
    # fields = ['title', 'content', 'order']

    form_class = PageForm

    template_name_suffix = '_update_form'

    # Es necesario sobreescribir el metodo para hacer reedirección al registro que estamos editando,
    # esto para acceder al objeto interno
    def get_success_url(self):
        # el 'ok', para validar si el registro se actualizo correctamente
        return reverse_lazy('pages:update', args=[self.object.id]) + '?ok'

@method_decorator(staff_member_required(), name='dispatch')
class PageDelete(DeleteView):
    model = Page

    success_url = reverse_lazy('pages:pages')

profiles/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
</head>
<body>
<body>
<!-- Navegación -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Playground</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned"
                aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:pages' %}">Páginas</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            Acceder
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">
                            Registrate
                        </a>
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">
                            Perfil
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">
                            Salir
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- Contenido -->
{% block content %}{% endblock %}
<!-- Javascript -->
<script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/js/main.js' %}"></script>
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-top:50px; text-align:center;">
    <h1>{{ title }}</h1>
    <p class="lead">CBV, autenticación, registros, perfiles y más</p>
  </div>
</div>
{% endblock %}

core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/includes/pages_menu.html
<!--Archivos para ckeditor--->
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<!--Archivo css para poner responsive el ckeditor del TextArea(content)-->
<link href="{% static 'pages/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:create' %}"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
    {% include 'pages/includes/pages_menu.html' %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <form action="" method="post">{% csrf_token %}
                            <p>¿Estás seguro de que quieres borrar <b>"{{ page }}"</b>?</p>
                            <div class="text-center">
                                <input class="btn btn-danger btn-block" type="submit" value="Sí, borrar la página"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

pages/templates/pages/page_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
    {% include 'pages/includes/pages_menu.html' %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{page.title}}</h2>
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'pages:update' page.id%}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
    {% include 'pages/includes/pages_menu.html' %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <form action="" method="post">{% csrf_token %}

                            {{ form.as_p }}

                            <br>
                            <div class="text-center">
                                <input class="btn btn-primary btn-block" type="submit" value="Crear página"/>
                            </div>
                            <br>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

pages/templates/pages/page_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
    {% include 'pages/includes/pages_menu.html' %}
    <main role="main">
        <div class="container mb-4">
            {% for page in page_list|dictsort:'id' reversed %}
                <div class="row mt-3">
                    <div class="col-md-9 mx-auto">
                        <h2 class="mb-4">{{ page.title }}</h2>
                        <div>
                            <p>{{ page.content|striptags|safe|truncatechars:"200" }}</p>
                            <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más</a>

                                {% if request.user.is_staff %}
                                    | <a href="{% url 'pages:update' page.id %}">Editar</a>
                                    | <a href="{% url 'pages:delete' page.id %}">Borrar</a>
                                {% endif %}

                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

pages/templates/pages/page_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
    {% include 'pages/includes/pages_menu.html' %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        {% if 'ok' in request.GET %}
                            <p style="color: green">
                                Pagina editada correctamente
                                <a href="{% url 'pages:page' page.id page.title|slugify %}">
                                    Haz click aqui para ver el resultado
                                </a>
                            </p>
                        {% endif %}
                        <form action="" method="post">{% csrf_token %}
                            <table>
                                {{ form.as_p }}
                            </table>
                            <br>

                            <div class="text-center">
                                <input class="btn btn-primary btn-block" type="submit" value="Actualizar página"/>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}